// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAls24XI_tVxt-engCd2PhfsY5fq9m-__s',
    appId: '1:341155992123:android:caaebd28f20a67737d821e',
    messagingSenderId: '341155992123',
    projectId: 'flutter-chat-app-ce756',
    storageBucket: 'flutter-chat-app-ce756.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1OS79-t27GWD_cNPBisr67_QClVGuRbQ',
    appId: '1:341155992123:ios:ec35367200f4f0697d821e',
    messagingSenderId: '341155992123',
    projectId: 'flutter-chat-app-ce756',
    storageBucket: 'flutter-chat-app-ce756.appspot.com',
    iosBundleId: 'com.example.mychat',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoMpPclVIOUft2wVpPKvsPLb0DCELBMzI',
    appId: '1:341155992123:web:39d06a61300a56517d821e',
    messagingSenderId: '341155992123',
    projectId: 'flutter-chat-app-ce756',
    authDomain: 'flutter-chat-app-ce756.firebaseapp.com',
    storageBucket: 'flutter-chat-app-ce756.appspot.com',
    measurementId: 'G-MP6D10Z3LS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1OS79-t27GWD_cNPBisr67_QClVGuRbQ',
    appId: '1:341155992123:ios:ec35367200f4f0697d821e',
    messagingSenderId: '341155992123',
    projectId: 'flutter-chat-app-ce756',
    storageBucket: 'flutter-chat-app-ce756.appspot.com',
    iosBundleId: 'com.example.mychat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoMpPclVIOUft2wVpPKvsPLb0DCELBMzI',
    appId: '1:341155992123:web:9bd99908e0a7caee7d821e',
    messagingSenderId: '341155992123',
    projectId: 'flutter-chat-app-ce756',
    authDomain: 'flutter-chat-app-ce756.firebaseapp.com',
    storageBucket: 'flutter-chat-app-ce756.appspot.com',
    measurementId: 'G-J630TJDD0Z',
  );

}